spring:
  properties:
    host-name: localhost
    feature-enabled:
      auto-upload: false
      auto-upload-meta: false
      feed-generation: true
      request-logging: true
    email:
      username: ${EMAIL_USERNAME:test}
      password: ${EMAIL_PASSWORD:test}
    cyclonedx:
      services:
        - 'localhost:9090'
        - 'localhost:9091'
        - 'localhost:9092'
        - 'localhost:9093'
        - 'localhost:9094'

logging:
  level:
    root: info
    com:
      github:
        regyl:
          gfi:
            service:
              impl:
                feed:
                  cyclonedx:
                    CycloneDxSbomConsumerImpl: INFO
                    homepage:
                      maven:
                        MavenPurlToBuildFileServiceImpl: INFO